### PR TITLE
Switch to CodeRay

### PR DESCRIPTION
**Pull request by bodrovis**
Per this discussion https://github.com/radar/forem/issues/512#issuecomment-38554189

If that seems like a way to go, I will play with styling a bit more. CodeRay allows to display line numbers and do some other fancy stuff.

### CODE REVIEW

**Comment by radar** [comment]
@bodrovis Do you have a screenshot showing what this looks like? What does the styling look like too?

**Comment by bodrovis** [comment]
@radar Well if you like the idea I will create a demo app on Heroku. Basically it paints words with different colors.

**Comment by bodrovis** [comment]
I cannot show it on Heroku because of these: https://github.com/radar/forem/issues/550 https://github.com/radar/forem/issues/552 but here is the screenshot:
coderay

**Comment by bodrovis** [comment]
@radar http://sitepoint-forem.herokuapp.com/forums/test1/topics/coderay you can check how this works here

**Comment by bodrovis** [comment]
@radar Use something like

```
<code class="ruby">
def test
puts "test"
end
</code>
```

in the posts.

**Comment by radar** [comment]
I won't have time to look at this before my wedding+honeymoon. You're on your own for the next 3 weeks.

Good luck.

**Comment by bodrovis** [comment]
@radar Yeah, I understand :) By the time you come back I will probably write an article about Forem for Sitepoint, will let you know. Have a really great time!!

**Pull request closed without merging**
